# Generated by Django 5.0.2 on 2024-02-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('industrySector', models.CharField(max_length=30)),
                ('websiteURL', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('currProgramme', models.CharField(max_length=50)),
                ('prevProgramme', models.CharField(max_length=50)),
                ('studyMode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('hybrid', 'Hybrid')], max_length=10)),
                ('studyPattern', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], max_length=2)),
                ('GPA', models.IntegerField()),
                ('desiredContractLength', models.CharField(choices=[('6-W', '6-weeks'), ('12-W', '12-weeks'), ('6-M', '6-months'), ('9-M', '9-months'), ('1-Y', '1-year')], max_length=25)),
                ('willingRelocate', models.BooleanField()),
                ('aspriations', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('superUserID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('privileges', models.CharField(choices=[('r', 'Read'), ('w', 'Write'), ('m', 'Maintain'), ('a', 'Admin')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('internshipID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contractMode', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('hybrid', 'Hybrid')], max_length=10)),
                ('contractPattern', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], max_length=2)),
                ('numberPositions', models.SmallIntegerField()),
                ('field', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('minGPA', models.SmallIntegerField()),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='internshipID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.internship'),
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiterID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('jobTitle', models.CharField(max_length=30)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='recruiterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter'),
        ),
        migrations.AddField(
            model_name='company',
            name='recruiterID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interviewID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=15)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('recruiterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recruiter')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='computedMatch',
            fields=[
                ('computedMatch', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('internshipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.internship')),
                ('interviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interview')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
        ),
    ]