# Generated by Django 5.0.2 on 2024-02-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='jobTitle',
            field=models.CharField(max_length=40),
        ),
    ]
