# Generated by Django 5.0.2 on 2024-02-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_recruiter_jobtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='aspriations',
            new_name='aspirations',
        ),
    ]
