# Generated by Django 4.2.6 on 2024-03-01 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_aspriations_student_aspirations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='internshipID',
        ),
    ]
