# Generated by Django 4.2.6 on 2024-03-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_company_internshipid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='recruiterID',
        ),
    ]
