# Generated by Django 4.2.6 on 2024-04-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_company_recruiterid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
