# Generated by Django 4.2.6 on 2024-04-13 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_internship_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedmatch',
            name='computedMatch',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='computedmatch',
            name='interviewID',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='core.interview'),
        ),
    ]
