# Generated by Django 4.2.6 on 2024-04-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_computedmatch_computedmatch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computedmatch',
            old_name='computedMatch',
            new_name='computedMatchID',
        ),
    ]
