# Generated by Django 4.2.6 on 2024-04-13 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_computedmatch_interviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='internshipID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.internship'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
