# Generated by Django 5.0.1 on 2024-04-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_recruiter_user'),
        ('core', '0010_interview_internshipid_alter_interview_interviewid'),
    ]

    operations = [
    ]
